log:
  level: warn
  file: "/tmp/mosdns.log"

include: []

plugins:
 
  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      exps:
        - "cn"
        - "arpa"
      files:
        - "/etc/mosdns/rule/whitelist.txt"
        - "/etc/mosdns/rule/google-cn.txt"
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_apple-cn.txt"
        - "/var/mosdns/geosite_category-games@cn.txt"
        - "/etc/mosdns/rule/trackers.txt"
        - "/etc/mosdns/rule/Microsoft.txt"
 #       - "/etc/mosdns/rule/apple-cn.txt"  #备用  = geosite_apple-cn
 #       - "/etc/mosdns/rule/direct-list.txt"  #备用  ~= geosite_cn

  # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/CN-ip-cidr.txt"
        - "/etc/mosdns/rule/lan.txt"
        - "/etc/mosdns/rule/china_ip6.txt"
#        - "/var/mosdns/geoip_cn.txt"  #弃用  < CN-ip-cidr

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"
        - "/etc/mosdns/rule/proxy-list.txt"
        - "/etc/mosdns/rule/telegram.txt"
#        - "/var/mosdns/geosite_geolocation-!cn.txt"   #弃用  < proxy-list
        
  # 广告域名
  - tag: advert
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/anti-ad.txt"
        - "/etc/mosdns/rule/blocklist.txt"

  # 重定向域名
  - tag: redirect
    type: redirect
    args:
      files:
        - "/etc/mosdns/rule/redirect.txt"

  # hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  # 转发至本地服务器
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: "127.0.0.1:5553"

  # 转发至加密服务器
  - tag: forward_tls
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "tls://223.5.5.5"
        - addr: "tls://223.6.6.6"
        - addr: "tls://1.12.12.12"
        
  # 转发至远程服务器
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: "127.0.0.1:7874"

  # 国内解析
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local

  # 加密服务器解析
  # 返回非国内 ip 则丢弃结果
  - tag: tls_sequence
    type: sequence
    args:
      - exec: $forward_tls
      - matches:
        - "!resp_ip $geoip_cn"
        - "has_resp"
        exec: drop_resp
      
  # 远程服务器解析
  # 远程服务器拒绝的则本地解析
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
      - matches:
        - rcode 2 5
        exec: $forward_local

  # fallback解析
  - tag: fallback
    type: fallback
    args:
      primary: tls_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:

      # 丢弃65类型请求 drop https query type 
      - matches:
        - qtype 65
        exec: reject 3
         
      # handle local ptr
      - matches:
        - qtype 12
        exec: reject 5
        
      # 去广告
      - matches:
        - qname $advert
        exec: reject 3

      # 匹配hosts
      - exec: $hosts
      - exec: jump has_resp_sequence
      
      # 域名重定向
      - exec: $redirect
    
      # 国内域名本地解析
      - matches:
        - qname $geosite_cn
        exec: $local_sequence
      - exec: jump has_resp_sequence

      # 国外域名远程解析
      - matches:
        - qname $geosite_no_cn
        exec: $forward_remote
      - exec: jump has_resp_sequence

      # 未命中域名fallback解析
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
